### ISSUE TITLE
Hi, when will the source code could be released?

### ISSUE THREAD

**Issue by rockywind** [georghess/neurad-studio#1]

**Comment by pierremerriaux-leddartech** [comment]
thanks for your very interesting works, same question...

**Comment by georghess** [comment]
Hi, thanks for your interest in this project! 

We are currently cleaning up the code and streamlining some interfaces. Our ambition is to release the code by early next year.

**Comment by rockywind** [comment]
Thank you for your reply!

**Comment by MartinEthier** [comment]
@georghess Hi Georg, thanks for the great work! Just wondering if you could give any more info on the code release timeline. Is it expected to be released within a few weeks or could it take a few months?

**Comment by georghess** [comment]
Hi @MartinEthier, our aim is to release it within a few weeks.

**Comment by 24werewolf** [comment]
> Hi @MartinEthier, our aim is to release it within a few weeks.

Hi Georg, thanks for the great work！ I would like to ask, will it be open sourced in February?

**Comment by JPenshornTAP** [comment]
Hi @georghess, do you have any updates regarding a potential release date?

**Comment by georghess** [comment]
Hi,

Due to the upcoming ECCV deadline, we've unfortunately had limited bandwidth to focus on the code release. But,  starting next week we'll give it more focus.

**Comment by zwlvd** [comment]
Hi @georghess ,is there any progress about the code release?
