### ISSUE TITLE
Tutorials about actor edits(removal, shift, add a new vehicle).

### ISSUE THREAD

**Issue by TurtleZhong** [georghess/neurad-studio#11]
I'm not sure if I missed something, but I think this project supports some editing operations for actors, as I have seen related examples in the paper. However, I didn't find any instructions regarding this in the usage documentation(README). I am wondering if there are any tutorials or additional links available that could provide guidance on this matter?

![image](https://github.com/georghess/neurad-studio/assets/19700579/2df159ac-752f-4e10-9523-73bbf258a656)

**Comment by carlinds** [comment]
Hi! You can modify actor trajectories by changing the position and orientation parameters held by the `DynamicActors`-class (see [nerfstudio/model_components/dynamic_actors.py](https://github.com/georghess/neurad-studio/blob/main/nerfstudio/model_components/dynamic_actors.py)).

We have implemented a few examples of modifications in our render scripts (see [https://github.com/georghess/neurad-studio/blob/main/nerfstudio/scripts/render.py](https://github.com/georghess/neurad-studio/blob/main/nerfstudio/scripts/render.py)). Have a look at `RenderInterpolated` and `DatasetRender` for some inspiration if you want to do your own custom edits.

**Comment by atonderski** [comment]
In the viewer there are also controls (bottom of the list) for experimenting with actor editing in realtime

**Comment by georghess** [comment]
Closing this for now, feel free to re-open if you find any issues with this :)

**Comment by amoghskanda** [comment]
> Hi! You can modify actor trajectories by changing the position and orientation parameters held by the `DynamicActors`-class (see [nerfstudio/model_components/dynamic_actors.py](https://github.com/georghess/neurad-studio/blob/main/nerfstudio/model_components/dynamic_actors.py)).
> 
> We have implemented a few examples of modifications in our render scripts (see https://github.com/georghess/neurad-studio/blob/main/nerfstudio/scripts/render.py). Have a look at `RenderInterpolated` and `DatasetRender` for some inspiration if you want to do your own custom edits.

and what if we want to edit actors individually using their uuid?Any insights on this?
