### ISSUE TITLE
Quality of rendering results is not ideal

### ISSUE THREAD

**Issue by sonnefred** [georghess/neurad-studio#17]
Hi, thanks for making this project open-sourced. I'm trying to train a model on Pandaset, but after 30000 iterations, I only get results like this, could you help me figure out what the reason is? Do I need to train it longer? Btw, I used parameter settings of a light-weighted version due to the limit of the gpu memory. Thanks 
![individualImage (1)](https://github.com/georghess/neurad-studio/assets/66628395/18e8a376-aebc-4a9d-89bc-239638aa7bb9)

**Comment by sonnefred** [comment]
> Hi, thanks for making this project open-sourced. I'm trying to train a model on Pandaset, but after 30000 iterations, I only get results like this, could you help me figure out what the reason is? Do I need to train it longer? Btw, I used parameter settings of a light-weighted version due to the limit of the gpu memory. Thanks ![individualImage (1)](https://private-user-images.githubusercontent.com/66628395/329562832-18e8a376-aebc-4a9d-89bc-239638aa7bb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTgwNDgsIm5iZiI6MTcxNTM5Nzc0OCwicGF0aCI6Ii82NjYyODM5NS8zMjk1NjI4MzItMThlOGEzNzYtYWViYy00YTlkLTg5YmMtMjM5NjM4YWE3YmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAzMjIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxY2RlZGMwOTgyZDlkNDY3ZDFhOWJlNzEyMjUyNmIyZjExYzEwNmQ1MjVkOTA3MTBiZGI5MTA3ZTRhMmM2ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FveHLe-RoH-qW4PfX6gZVC3BGe03a4Ef7n7DJB42hNk)

I trained the model for longer time, but the rendered images seem still colorless, what may cause this? Thanks.

**Comment by amoghskanda** [comment]
did you use Neurad tiny?

**Comment by sonnefred** [comment]
> did you use Neurad tiny?

I think so, because when I used default Neurad, Bus Error occured. In other issues, I saw someone also encountered this problem and the author suggested to use a tiny version. Do you face the same problem?

**Comment by atonderski** [comment]
the "neurad-tiny" launch config is and extremely downscaled version of neurad and not an official or recommended version for actual use. Rather it is useful for local debugging etc.

Besides the much smaller model capacity, 30.000 iterations with neurad-tiny is still much fewer rays than 20.000 iterations with regular neurad, which likely also contributes to the poor results you observe. I recommend pushing the settings as close to the default neurad settings as you can fit on your machine, and increase the batch size (num rays per train step)

**Comment by sonnefred** [comment]
> the "neurad-tiny" launch config is and extremely downscaled version of neurad and not an official or recommended version for actual use. Rather it is useful for local debugging etc.
> 
> Besides the much smaller model capacity, 30.000 iterations with neurad-tiny is still much fewer rays than 20.000 iterations with regular neurad, which likely also contributes to the poor results you observe. I recommend pushing the settings as close to the default neurad settings as you can fit on your machine, and increase the batch size (num rays per train step)

Thanks for your reply, I will have a try.
