### ISSUE TITLE
Lidar rendering for neuradest

### ISSUE THREAD

**Issue by amoghskanda** [georghess/neurad-studio#20]
Hey!Thanks for making this open-source. I used neuradest for training and I was editing actor trajectories by adding shifts to actors and rendering interpolated videos. The paper mentioned that lidar simulation was possible for neurad. Any insights on how to get the lidar rendering for neuradest?

**Comment by alchemz** [comment]
@amoghskanda I opened a request here https://github.com/georghess/neurad-studio/issues/21 Do you know how to do actor edits in this neurad codebase? Thanks for your help!

**Comment by amoghskanda** [comment]
@georghess @atonderski how do I get the lidar rendering for neurad? I went through the render file and there's no option to model the lidar data. The paper mentions lidar simulation is possible but nothing about how it's done. Thanks

**Comment by alchemz** [comment]
<img width="333" alt="Screenshot 2024-05-16 at 9 58 06 PM" src="https://github.com/georghess/neurad-studio/assets/10191088/d89cbc42-1272-4049-94bf-3f60de7a0f73">

@amoghskanda There is a lidar rendering option under reviewer, I played with it, but nothing got rendered. Have you tried it?

**Comment by alchemz** [comment]
I got the lidar rendering working in the viewer, but honestly it looks a bit funky.

<img width="1173" alt="Screenshot 2024-05-16 at 10 05 38 PM" src="https://github.com/georghess/neurad-studio/assets/10191088/373e4bf8-c918-45ed-971d-b850367930d5">

**Comment by amoghskanda** [comment]
I haven't tried it becase I wasn't able to render interpolated trajectory after actor edits using viewer. Viewer only helped in visualization and the in the render using viewer, only the camera sensor was moving as per camera path, rest of the actors were static. I want to render lidar from the codebase and was asking if that's possible. Anyway will checkout the viewer's lidar render

**Comment by amoghskanda** [comment]
> I got the lidar rendering working in the viewer, but honestly it looks a bit funky.
> <img alt="Screenshot 2024-05-16 at 10 05 38 PM" width="1173" src="https://private-user-images.githubusercontent.com/10191088/331465659-373e4bf8-c918-45ed-971d-b850367930d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjMwNzUsIm5iZiI6MTcxNTkyMjc3NSwicGF0aCI6Ii8xMDE5MTA4OC8zMzE0NjU2NTktMzczZTRiZjgtYzkxOC00NWVkLTk3MWQtYjg1MDM2NzkzMGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA1MTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NzBjODFhOTIwNjljNDRhOTQxMjNlMjYzMGY3Y2MwYTJhOWVhMDIzOTQzNTZkMGNlNWM3ODY2YjYxNjQzNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dd5gdiOQVuFZ3BM9JYk6sL5-DUIw-z8RBZgXnFPGDik">

is this a screenshot from the viewer or were you able to download it?

**Comment by alchemz** [comment]
This is a screenshot of the viewer. I looked through the code base, only viewer supports lidar rendering. 

There is a `LidarRenderer` takes input from viewer control and renders lidar, potentially this can be rewrite to take inputs from the code and render lidar. 
https://github.com/georghess/neurad-studio/blob/12745d34426eb732259be35cb7bb4fb04c4df7a1/nerfstudio/viewer/render_state_machine.py#L361-L366

**Comment by amoghskanda** [comment]
> and

Have you tried it?

**Comment by alchemz** [comment]
No. I have not. I want to get some clarity from the authors first.

**Comment by FCInter** [comment]
> No. I have not. I want to get some clarity from the authors first.

姐，你的渲染结果是怎么出来的，我训完跑run_viewer.py只显示了训练图片和lidar点云，没有渲染效果

**Comment by georghess** [comment]
We've only implemented a lidar renderer in the viewer currently, and not as a render-command. For our experiments, we saved point clouds at eval by using the predicted depth and thresholding using the ray drop probability. I'll add a lidar renderer to our to do's, but not sure when it will be done. So, if you implement one, feel free to open a PR :)  

@alchemz In what sense do the point clouds look funky? The image looks like you are rendering PCA of features rather than RGB, if that is what you are referring to.

**Comment by amoghskanda** [comment]
> We've only implemented a lidar renderer in the viewer currently, and not as a render-command. For our experiments, we saved point clouds at eval by using the predicted depth and thresholding using the ray drop probability. I'll add a lidar renderer to our to do's, but not sure when it will be done. So, if you implement one, feel free to open a PR :)
> 
> @alchemz In what sense do the point clouds look funky? The image looks like you are rendering PCA of features rather than RGB, if that is what you are referring to.

Essentially, what I was trying to do is render lidar point clouds for actors with modified trajectory. I saved the depth and intensity data as .npy files and tried to render lidar pointclouds from that but not sure if that's correct.

**Comment by georghess** [comment]
To clarify, our point clouds were generated as `pc = origin + direction * expected_depth` and then masked `pc = pc[existance_prob>thres]`

**Comment by Crescent-Saturn** [comment]
> Hi,
> 
> I've now added an argument for rendering point clouds in the render script. However, I would view it more as an example. Feel free to open a pull-request if you implement something more sophisticated. :)

Hi @carlinds , I find it useful when rendering the point clouds with the script.

In addition, I wonder if you accept a small modification (PR) that plotting as well the gt-lidar points for comparison in the script?

That would be very helpful. Thanks!

**Comment by georghess** [comment]
@Crescent-Saturn Go ahead and open a PR for any useful features :)

**Comment by Crescent-Saturn** [comment]
> @Crescent-Saturn Go ahead and open a PR for any useful features :)

Yeah, in fact, there will be a PR of waymo dataparser soon which contains this modification as well. :rocket:
