### ISSUE TITLE
How to render the real world vision

### ISSUE THREAD

**Issue by FCInter** [georghess/neurad-studio#24]
I'm training and following the README.md, I listen on the port. But I got the rendered depth or intensity like this

![image](https://github.com/georghess/neurad-studio/assets/20165927/54a0b159-4a83-4b88-81a9-6be2dbb845ef)

I want to get the rendered real world image. What shall I do?

Thx.

**Comment by georghess** [comment]
The output type is set to features, rather than rgb in your image
