### ISSUE TITLE
Render Individual Actors with Trajectory Edits

### ISSUE THREAD

**Issue by alchemz** [georghess/neurad-studio#29]
**Is your feature request related to a problem? Please describe.**
In the neurad paper, there is a figure showing actor edits for individual vehicles. However using `neurad-studio-main/nerfstudio/scripts/render.py`, it applies the same `actor_shift` for all vehicles. There is more to desire for the rendering controllability.

<img width="1224" alt="Screenshot 2024-05-31 at 9 39 10 PM" src="https://github.com/georghess/neurad-studio/assets/10191088/a3a49c97-4991-48af-9625-4540f37db032">

**Describe the solution you'd like**
Could you please share which part of the code does individual actor edits ?

**Describe alternatives you've considered**
Actor shift is applied to all dynamic actors through the below line, I think we can use the actor_index and assign shift to the target objects. However it is hard to associate the index with objects in the scene.
`pipeline.model.dynamic_actors.actor_positions += actor_shift`

**Additional context**
I wonder if it is possible to edit the stationary objects as well ?

**Comment by georghess** [comment]
Hi,

When creating these qualitative examples, we've added some elements to the viewer to identify which actor is which. I'll ask @carlinds to push it, either to the main branch or a separate one. I agree that it would be nice to have an intuitive way/GUI to easily edit individual actors, but we haven't had time to work on this.

As for editing stationary objects, the current code does not support it out of the box. But, it shouldn't be too hard to add some concept of shifting parts of the static environment with some bounding box. However, renderings of the area that is revealed when moving something static will of course look rather bad.

**Comment by carlinds** [comment]
Hi,

I have added some functionality for individual actor editing now. As Georg mentioned, we don't have any nice GUI for easily editing right now but I've added some functionality to the viewer that lets you choose which actor to edit. In addition, I also added an argument for this in the render scripts.

Feel free to open a pull-request if you have any improvements on this setup! :)
