### ISSUE TITLE
Train fails when parsing ZOD dataset

### ISSUE THREAD

**Issue by zachytong** [georghess/neurad-studio#31]
Hi author,

Thanks for your great work! 

I am trying to train the model on ZOD dataset. But in parsing the dataset, it returns FileNotFoundError: [Errno 2] No such file or directory: 'data/zod/auto_annotations/sequences/000581.json'. 

I use transmission-remote to download the torrent of sequences part of the dataset and unzip them under the data subdirectory. But no auto_annotations directory is generated anyway.

I noticed comments in ZodDataParserConfig indicating that To create these masks, install zod and run `zod generate object-masks`, I tried but zod seems to not have this subcommand (No such command 'object-masks'.). 

Is there anything missing when downloading and preprocessing the zod sequences dataset? Thanks!

**Comment by georghess** [comment]
Hi,

Thank you for raising this issue! I think the auto annotations are not part of the official ZOD download yet. We'll have to figure out the best way to distribute them. For now, here's a zip-file (unzip in your ZOD root directory).

[auto_annotations.zip](https://github.com/user-attachments/files/15773566/auto_annotations.zip)

**Comment by zachytong** [comment]
> Hi,
> 
> Thank you for raising this issue! I think the auto annotations are not part of the official ZOD download yet. We'll have to figure out the best way to distribute them. For now, here's a zip-file (unzip in your ZOD root directory).
> 
> [auto_annotations.zip](https://github.com/user-attachments/files/15773566/auto_annotations.zip)

Hi Georghess, thanks for your kind reply, do you consider adding a comment in the data part in README? It will be more clear for those who want to try on ZOD dataset could jump here and download the auto_annotations.zip : ) Since the problem is perfectly solved I am going to close this issue.

**Comment by georghess** [comment]
Hi,

Yeah, I'll add a link to the readme :)
