### ISSUE TITLE
training with --mixed-precision False is not working 

### ISSUE THREAD

**Issue by karericegood** [georghess/neurad-studio#34]
**Describe the bug**

Hi, thank you so much for opening this great research. I'm trying to train your model with only FP32. In the process, I set --mixed-precision False and tried to run the experiment and found the following error message.

![image](https://github.com/georghess/neurad-studio/assets/48081761/afba72f2-e672-46d1-9db1-f1a61201767f)

**To Reproduce**
After I've done all the work for the installation, I entered the following command

python ./nerfstudio/scripts/train.py neurad --mixed-precision False pandaset-data

Thanks!

**Comment by georghess** [comment]
Hi,

We've probably never turned off mixed precision. Should be fixed by 8e3daba, let me know if that is not the case.
