### ISSUE TITLE
python nerfstudio/scripts/train.py neurad pandaset-data meets  error

### ISSUE THREAD

**Issue by zjcs** [georghess/neurad-studio#35]
thans for your great work.when i use the docker,and root@4133cb1494b4:/workspace# python nerfstudio/scripts/train.py neurad pandaset-data
╭─ Parsing error ──────────────────────────────────────────────────────────────╮
│ Argument                                                                     │
│ {depth-nerfacto,dnerf,generfacto,instant-ngp,instant-ngp-bounded,mipnerf,ner │
│ facto,nerfacto-big,nerfacto-huge,neus,neus-facto,phototourism,semantic-nerfw │
│ ,splatfacto,splatfacto-big,tensorf,vanilla-nerf,BioNeRF,igs2gs,in2n,in2n-sma │
│ ll,in2n-tiny,kplanes,kplanes-dynamic,lerf,lerf-big,lerf-lite,nerfgs,nerfplay │
│ er-nerfacto,nerfplayer-ngp,nerfsh,pynerf,pynerf-occupancy-grid,pynerf-synthe │
│ tic,seathru-nerf,seathru-nerf-lite,signerf,signerf_nerfacto,tetra-nerf,tetra │
│ -nerf-original,volinga,zipnerf}: invalid choice: 'neurad' (choose from       │
│ 'depth-nerfacto', 'dnerf', 'generfacto', 'instant-ngp',                      │
│ 'instant-ngp-bounded', 'mipnerf', 'nerfacto', 'nerfacto-big',                │
│ 'nerfacto-huge', 'neus', 'neus-facto', 'phototourism', 'semantic-nerfw',     │
│ 'splatfacto', 'splatfacto-big', 'tensorf', 'vanilla-nerf', 'BioNeRF',        │
│ 'igs2gs', 'in2n', 'in2n-small', 'in2n-tiny', 'kplanes', 'kplanes-dynamic',   │
│ 'lerf', 'lerf-big', 'lerf-lite', 'nerfgs', 'nerfplayer-nerfacto',            │
│ 'nerfplayer-ngp', 'nerfsh', 'pynerf', 'pynerf-occupancy-grid',               │
│ 'pynerf-synthetic', 'seathru-nerf', 'seathru-nerf-lite', 'signerf',          │
│ 'signerf_nerfacto', 'tetra-nerf', 'tetra-nerf-original', 'volinga',          │
│ 'zipnerf')                                                                   │
│ ──────────────────────────────────────────────────────────────────────────── │
│ For full helptext, run train.py --help                                       │

also,pandaset-data is not work

**Comment by Andyshen555** [comment]
Hi, when I am building the docker, I ran into

> [15/18] RUN cd /nerfstudio && python3.10 -m pip install --no-cache-dir -e .:                  
0.554 Obtaining file:///nerfstudio                                                               
0.554 ERROR: file:///nerfstudio does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
------
Dockerfile:146
--------------------
 144 |     
 145 |     # Install nerfstudio dependencies.
 146 | >>> RUN cd /nerfstudio && python3.10 -m pip install --no-cache-dir -e .
 147 |     
 148 |     # Make sure viser client is built
--------------------
ERROR: failed to solve: process "/bin/bash -c cd /nerfstudio && python3.10 -m pip install --no-cache-dir -e ." did not complete successfully: exit code: 1

Can you please elaborate on how to solve this problem? Thank you.

**Comment by georghess** [comment]
How are you building your docker? Did you clone this repo and then run `docker build -t neurad .`?

@zjcs your trace looks like you are trying to run nerfstudio, not neurad-studio, as many of those methods are not in our [method_config.py](https://github.com/georghess/neurad-studio/blob/main/nerfstudio/configs/method_configs.py).

**Comment by zjcs** [comment]
> Hi, when I am building the docker, I ran into
> 
> ```
> > [15/18] RUN cd /nerfstudio && python3.10 -m pip install --no-cache-dir -e .:                  
> 0.554 Obtaining file:///nerfstudio                                                               
> 0.554 ERROR: file:///nerfstudio does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
> ------
> Dockerfile:146
> --------------------
>  144 |     
>  145 |     # Install nerfstudio dependencies.
>  146 | >>> RUN cd /nerfstudio && python3.10 -m pip install --no-cache-dir -e .
>  147 |     
>  148 |     # Make sure viser client is built
> --------------------
> ERROR: failed to solve: process "/bin/bash -c cd /nerfstudio && python3.10 -m pip install --no-cache-dir -e ." did not complete successfully: exit code: 1
> ```
> 
> Can you please elaborate on how to solve this problem? Thank you.

It seems a long time after I met this issue. In my memory, it seems that you should update the setuptools to higher version. But I am not sure, this issue is due to the new python projection manangement, toml instead of setup.py.

**Comment by zjcs** [comment]
> How are you building your docker? Did you clone this repo and then run `docker build -t neurad .`?
> 
> @zjcs your trace looks like you are trying to run nerfstudio, not neurad-studio, as many of those methods are not in our [method_config.py](https://github.com/georghess/neurad-studio/blob/main/nerfstudio/configs/method_configs.py).

Thanks for your reply. I almost have forgot this issuse since other work. It seems that you are right, but I have no time to check it.

**Comment by georghess** [comment]
I should mention that there seem to be some installation issues, as raised in #33. Investigating this currently.

**Comment by Andyshen555** [comment]
@zjcs @georghess Thank you very much for the help. I was new to docker and had no idea that running ```docker build -< Dockerfile``` does not link to my local folder. For anyone that runs into time out during ```pip install -e .```, I had the problem solved by tightening the version check in .toml for torch and torchmetrics.

**Comment by georghess** [comment]
@Andyshen555 could you elaborate on what spans of versions you used?

**Comment by Andyshen555** [comment]
I specifically set:
```
"setuptools==69.5.1,"
...
"torch==2.0.1",
"torchvision==0.15.2",
"torchmetrics[image]==1.3.2"
```
Works with cu117 and cu118, both tested.
When using the original .toml, both my docker and my conda env had a problem that tried to install torchmetrics 1.4.0 but could not solve dependencies conflicts with torch.

**Comment by zjcs** [comment]
-e option is no need, remove this option and try anain,I am not sure

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/02/2024 22:10 |
| To | georghess/neurad-studio ***@***.***> |
| Cc | zjcs ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [georghess/neurad-studio] python nerfstudio/scripts/train.py neurad pandaset-data meets error (Issue #35) |

I specifically set:

"setuptools==69.5.1,"
...
"torch==2.0.1",
"torchvision==0.15.2",
"torchmetrics[image]==1.3.2"


Works with cu117 and cu118, both tested.
When using the original .toml, both my docker and my conda env had a problem that tried to install torchmetrics 1.4.0 but could not solve dependencies conflicts with torch.

**Comment by georghess** [comment]
After some digging, I found that pinning `numpy<2.0` should resolve installation issues. Let me know if you need any further help.
