### ISSUE TITLE
nerfstuidio not found

### ISSUE THREAD

**Issue by Andyshen555** [georghess/neurad-studio#37]
I have installed the neurad-studio as required. However, when I try to train the model, it gives me:

python nerfstudio/scripts/train.py neurad pandaset-data --data /mnt/ssd/xxx/data/pandaset/
Traceback (most recent call last):
  File "/mnt/ssd/xxx/neurad-studio/nerfstudio/scripts/train.py", line 69, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/mnt/ssd/xxx/neurad-studio/nerfstudio/configs/method_configs.py", line 28, in <module>
    from nerfstudio.cameras.camera_optimizers import CameraOptimizerConfig, ScaledCameraOptimizerConfig
  File "/mnt/ssd/xxx/neurad-studio/nerfstudio/cameras/camera_optimizers.py", line 32, in <module>
    from nerfstudio.cameras.cameras import Cameras
  File "/mnt/ssd/xxx/neurad-studio/nerfstudio/cameras/cameras.py", line 31, in <module>
    import nerfstudio.utils.math
  File "/mnt/ssd/xxx/neurad-studio/nerfstudio/utils/math.py", line 27, in <module>
    from nerfstudio.data.scene_box import OrientedBox
ModuleNotFoundError: No module named 'nerfstudio.data.scene_box'

Am I missing some steps during the setup? I am running at the root folder of /mnt/ssd/xxx/neurad-studio.
Any help is appreciated. Thanks in advance.

**Comment by JulienStanguennec-Leddartech** [comment]
Maybe you have missed the installation of the neurad-package iself ?
**[Install neurad:](https://github.com/georghess/neurad-studio?tab=readme-ov-file#installing-neurad)** After cloning the repo make sure you install it:
```
git clone https://github.com/georghess/neurad-studio.git
cd neurad-studio
pip install --upgrade pip setuptools
pip install -e .
``` 

Make sure you verify the installation steps from the README.md:
1. Create conda environement: https://github.com/georghess/neurad-studio?tab=readme-ov-file#create-environment
2. Install dependencies: https://github.com/georghess/neurad-studio?tab=readme-ov-file#dependencies
3. Install neurad: https://github.com/georghess/neurad-studio?tab=readme-ov-file#installing-neurad

**Comment by Andyshen555** [comment]
Very interestingly, I found that I cannot properly install it using python 3.8. I switched to python 3.10 and everything installed properly. But for py3.10 the .toml didn't work properly, maybe its my conda problem. Thx anyways.
