### ISSUE TITLE
How to adjust the start frame and end frame

### ISSUE THREAD

**Issue by sonnefred** [georghess/neurad-studio#38]
Hi, I want to train a model just using part of images of a sequence. Where can I set the start frame and end frame easily? Thanks.

**Comment by JulienStanguennec-Leddartech** [comment]
I think the following fields from the dataparser could help you out:

```python
    dataset_start_fraction: float = 0.0
    """At what fraction of the dataset to start."""
    dataset_end_fraction: float = 1.0
    """At what fraction of the dataset to end."""
```

See in .vscode/launch.json file for example: https://github.com/georghess/neurad-studio/blob/main/.vscode/launch.json#L73

![image](https://github.com/georghess/neurad-studio/assets/44166203/a6ea1616-ac2c-4a8c-8d40-38ca1cddbc32)

**Comment by sonnefred** [comment]
> I think the following fields from the dataparser could help you out:
> 
> ```python
>     dataset_start_fraction: float = 0.0
>     """At what fraction of the dataset to start."""
>     dataset_end_fraction: float = 1.0
>     """At what fraction of the dataset to end."""
> ```
> 
> See in .vscode/launch.json file for example: https://github.com/georghess/neurad-studio/blob/main/.vscode/launch.json#L73
> 
> ![image](https://private-user-images.githubusercontent.com/44166203/343228526-a6ea1616-ac2c-4a8c-8d40-38ca1cddbc32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTYxMzksIm5iZiI6MTcxOTQ1NTgzOSwicGF0aCI6Ii80NDE2NjIwMy8zNDMyMjg1MjYtYTZlYTE2MTYtYWMyYy00YThjLThkNDAtMzhjYTFjZGRiYzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAyMzcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjU5MDBmMGEyNWE5ZmM2MDRjNDEzNDAyMzk0OTMxOTgxN2Q2ZWY2ODI5MThjMzNmYzJjNWZmZGJhMWE3MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W-e6FFO5qkZcQxf0bsEJAULAJ-l03ed8g0mbCioASrs)

OK, thank you, I will have a try.
