### ISSUE TITLE
RuntimeError: FIND was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by sonnefred** [georghess/neurad-studio#39]
Hi, I have met this error, which may be related to cuda version. 
![图片](https://github.com/georghess/neurad-studio/assets/66628395/e8554bb9-f94c-455a-9322-23378bd174bb)
I have checked my settings, and the versions of pytorch and cuda are as following. Do you know how to solve this problem? Thanks.
![图片](https://github.com/georghess/neurad-studio/assets/66628395/81e34162-dde7-45ff-bb19-2c3a1c76120e)

**Comment by Andyshen555** [comment]
Please check your Nvidia driver. It is likely due to your driver is too old / not installed properly.
