### ISSUE TITLE
Small bug in neurad-2x-paper method config

### ISSUE THREAD

**Issue by vnmusat** [georghess/neurad-studio#46]
The dictionary key used should be "neurad-2x-paper" otherwise the flip_prob is still the one inherited from neurader (0.5)

https://github.com/georghess/neurad-studio/blob/4c768c76e37244fe58d79926f53354628ac4329a/nerfstudio/configs/method_configs.py#L420

**Comment by atonderski** [comment]
thanks for pointing this out :) fixed
