### ISSUE TITLE
Docker Build Errors

### ISSUE THREAD

**Issue by MartinEthier** [georghess/neurad-studio#5]
When trying to build the docker image, I run into a few issues. First, I get the following error:

![neurad_docker_error](https://github.com/georghess/neurad-studio/assets/29309901/b97b952d-d0b1-460f-94c3-2c0151618b52)

This seems to be due to the command using bash specific syntax. I am using Ubuntu which means the docker commands are ran using /bin/sh instead of /bin/bash. This can be fixed by replacing the CUDA_VER assignment to something that does not use bash specific syntax:

`CUDA_VER=$(echo $CUDA_VERSION | awk 'BEGIN{FS=OFS="."}NF--' | sed -e 's/\.//g')`

After fixing the previous error I then I get another error:

![image](https://github.com/georghess/neurad-studio/assets/29309901/43024bd3-3ed6-4cbb-9e6d-48eaedc1407b)

I haven't been able to fix this issue yet. I'm wondering if you have any ideas on what is going wrong.

**Comment by carlinds** [comment]
Hi! Thanks for reporting this issue. I see that we missed a line in the dockerfile, which should set the default shell to bash and solve your first issue. Adding the following before the torch installation should work:

`SHELL ["/bin/bash", "-c"]`

The second error can be resolved by changing back the project name in pyproject.toml to "nerfstudio".

I will put up a fix with both of these changes.

**Comment by TurtleZhong** [comment]
> Hi! Thanks for reporting this issue. I see that we missed a line in the dockerfile, which should set the default shell to bash and solve your first issue. Adding the following before the torch installation should work:
> 
> `SHELL ["/bin/bash", "-c"]`
> 
> The second error can be resolved by changing back the project name in pyproject.toml to "nerfstudio".
> 
> I will put up a fix with both of these changes.

Hi, Following your solution, I have fixed in the tiny-cuda-nn install step, I also have changed back the project name in pyproject.toml to "nerfstudio", but I still failed in this command `RUN ns-install-cli --mode install`, I got error like this:

```
=> [15/17] RUN cd /nerfstudio && python3.10 -m pip install --no-cache-dir -e .                        190.4s
 => [16/17] WORKDIR /workspace                                                                           0.1s  => ERROR [17/17] RUN ns-install-cli --mode install                                                     10.2s ------                                                                                                        
 > [17/17] RUN ns-install-cli --mode install:                                                                 #0 0.345 [09:17:56] 🤷 .zshrc not found, skipping.                                                                 install.py:369                                                                                           
#0 0.346            🔍 Found .bashrc!                                                                              install.py:371                                                                                           
#0 0.609            ✔ Wrote new completion to /nerfstudio/nerfstudio/scripts/completions/bash/_ns-dev-test!        install.py:133
#0 0.636            ✔ Wrote new completion to /nerfstudio/nerfstudio/scripts/completions/bash/_ns-install-cli!     install.py:133
#0 2.826 [09:17:58] ✔ Wrote new completion to                                                                      install.py:133
#0 2.826            /nerfstudio/nerfstudio/scripts/completions/bash/_ns-dev-sync-viser-message-defs!                             
#0 3.454 [09:17:59] ✔ Wrote new completion to /nerfstudio/nerfstudio/scripts/completions/bash/_ns-download-data!   install.py:133
#0 3.809            ✔ Wrote new completion to /nerfstudio/nerfstudio/scripts/completions/bash/_ns-process-data!    install.py:133
#0 6.006 [09:18:01] ✔ Wrote new completion to /nerfstudio/nerfstudio/scripts/completions/bash/_ns-render!          install.py:133
#0 6.043            ✔ Wrote new completion to /nerfstudio/nerfstudio/scripts/completions/bash/_ns-viewer!          install.py:133
#0 6.127            ✔ Wrote new completion to /nerfstudio/nerfstudio/scripts/completions/bash/_ns-eval!            install.py:133
#0 6.616 [09:18:02] ❌ Completion script generation failed: ['ns-export', '--tyro-print-completion', 'bash']       install.py:123
#0 6.619            Traceback (most recent call last):                                                             install.py:127
#0 6.619              File "/usr/local/bin/ns-export", line 5, in <module>                                                       
#0 6.619                from nerfstudio.scripts.exporter import entrypoint                                                       
#0 6.619              File "/nerfstudio/nerfstudio/scripts/exporter.py", line 43, in <module>                                    
#0 6.619                from nerfstudio.fields.sdf_field import SDFField  # noqa                                                 
#0 6.619            ModuleNotFoundError: No module named 'nerfstudio.fields.sdf_field'                                           
#0 6.619                                                                                                                         
#0 6.620 Traceback (most recent call last):
#0 6.620   File "/usr/local/bin/ns-install-cli", line 8, in <module>
#0 6.620     sys.exit(entrypoint())
#0 6.620   File "/nerfstudio/nerfstudio/scripts/completions/install.py", line 411, in entrypoint
#0 6.621     tyro.cli(main, description=__doc__)
#0 6.621   File "/usr/local/lib/python3.10/dist-packages/tyro/_cli.py", line 184, in cli
#0 6.621     output = _cli_impl(
#0 6.621   File "/usr/local/lib/python3.10/dist-packages/tyro/_cli.py", line 446, in _cli_impl
#0 6.621     out, consumed_keywords = _calling.call_from_args(
#0 6.621   File "/usr/local/lib/python3.10/dist-packages/tyro/_calling.py", line 241, in call_from_args
#0 6.621     return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
#0 6.621   File "/nerfstudio/nerfstudio/scripts/completions/install.py", line 392, in main
#0 6.621     _generate_completions_files(completions_dir, scripts_dir, shells_supported, shells_found)
#0 6.621   File "/nerfstudio/nerfstudio/scripts/completions/install.py", line 323, in _generate_completions_files
#0 6.622     completion_paths = list(
#0 6.622   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
#0 6.622     yield _result_or_cancel(fs.pop())
#0 6.622   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
#0 6.622     return fut.result(timeout)
#0 6.622   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
#0 6.622     return self.__get_result()
#0 6.622   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
#0 6.623     raise self._exception
#0 6.623   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
#0 6.623     result = self.fn(*self.args, **self.kwargs)
#0 6.623   File "/nerfstudio/nerfstudio/scripts/completions/install.py", line 325, in <lambda>
#0 6.623     lambda path_or_entrypoint_and_shell: _generate_completion(
#0 6.623   File "/nerfstudio/nerfstudio/scripts/completions/install.py", line 128, in _generate_completion
#0 6.623     raise e
#0 6.623   File "/nerfstudio/nerfstudio/scripts/completions/install.py", line 115, in _generate_completion
#0 6.623     new = subprocess.run(
#0 6.623   File "/usr/lib/python3.10/subprocess.py", line 526, in run
#0 6.624     raise CalledProcessError(retcode, process.args,
#0 6.624 subprocess.CalledProcessError: Command '['ns-export', '--tyro-print-completion', 'bash']' returned non-zero exit status 1.
#0 10.16 [09:18:05] ✔ Wrote new completion to /nerfstudio/nerfstudio/scripts/completions/bash/_ns-train!           install.py:133
------
Dockerfile:154
--------------------
 152 |     SHELL ["/bin/sh", "-c"]
 153 |     # Install nerfstudio cli auto completion
 154 | >>> RUN ns-install-cli --mode install
 155 |     
 156 |     # Bash as default entrypoint.
--------------------
ERROR: failed to solve: process "/bin/sh -c ns-install-cli --mode install" did not complete successfully: exit code: 1
```

I haven't been able to fix this issue yet. I'm wondering if you have any ideas on what is going wrong.

**Comment by carlinds** [comment]
Hi! This has already been fixed in the latest version. Please pull the latest changes and try again :)

**Comment by HulkM** [comment]
Hi! I meet some new wrong that shows in 79th row of Dockerfile. 
![2665608051](https://github.com/georghess/neurad-studio/assets/50734275/29a36de9-46c0-4b04-93dc-8fac81425667)

**Comment by Crescent-Saturn** [comment]
> Hi! I meet some new wrong that shows in 79th row of Dockerfile. ![2665608051](https://private-user-images.githubusercontent.com/50734275/325276189-29a36de9-46c0-4b04-93dc-8fac81425667.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzI5NjQsIm5iZiI6MTcxMzk3MjY2NCwicGF0aCI6Ii81MDczNDI3NS8zMjUyNzYxODktMjlhMzZkZTktNDZjMC00YjA0LTkzZGMtOGZhYzgxNDI1NjY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE1MzEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMGZkZmM2ZWM2OWY4ODMzNzhhNTkzMTY1YTc2YjNhMTI0ODc0MjU1NThmY2VkYzdjMmRhZmI5ZGM4ODY4MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xRAcszo6Kz02wmO8TiVevncRbWrMvYhuKQBPKqW-Kk8)

@HulkM Hi, check the connection to https://ceres-solver.googlesource.com/ceres-solver.git. It is not easy when you are in China mainland. Most google services seems to be blocked. Good luck:
![image](https://github.com/georghess/neurad-studio/assets/18294546/ca7a547d-3cee-42f9-80cf-74ce6a46c868)

**Comment by TurtleZhong** [comment]
> Hi! This has already been fixed in the latest version. Please pull the latest changes and try again :)

I have tried the latest version, and it's OK.
