### ISSUE TITLE
Dynamic rigid actors'appearance from  non-visible angles

### ISSUE THREAD

**Issue by zzz5y** [georghess/neurad-studio#53]
Thanks for your great work!
How does Neurad address the appearance of dynamic rigid actors from non-visible angles

**Comment by georghess** [comment]
We have a (left-right) symmetry prior, so we can handle some non-visible angles. But we don't handle other non-visible angles, e.g., rendering the front of a car that has been seen only from behind

**Comment by zzz5y** [comment]
thanks for your reply!

**Comment by zzz5y** [comment]
> We have a (left-right) symmetry prior, so we can handle some non-visible angles. But we don't handle other non-visible angles, e.g., rendering the front of a car that has been seen only from behind

thanks for your reply!

**Comment by zzz5y** [comment]
> We have a (left-right) symmetry prior, so we can handle some non-visible angles. But we don't handle other non-visible angles, e.g., rendering the front of a car that has been seen only from behind

can you please give any code link  about the  symmetry prior ?thanks a lot

**Comment by wjie-gogogo** [comment]
> > We have a (left-right) symmetry prior, so we can handle some non-visible angles. But we don't handle other non-visible angles, e.g., rendering the front of a car that has been seen only from behind
> 
> can you please give any code link about the symmetry prior ?thanks a lot

I think it could be https://github.com/georghess/neurad-studio/blob/b7012ac5ac41c8ac86a63ba7ba799bd27a57d2f0/nerfstudio/field_components/neurad_encoding.py#L211

**Comment by georghess** [comment]
Exactly. During training, we randomly flip actors to supervise both sides of them.

**Comment by zzz5y** [comment]
> > > We have a (left-right) symmetry prior, so we can handle some non-visible angles. But we don't handle other non-visible angles, e.g., rendering the front of a car that has been seen only from behind
> > 
> > 
> > can you please give any code link about the symmetry prior ?thanks a lot
> 
> I think it could be
> 
> https://github.com/georghess/neurad-studio/blob/b7012ac5ac41c8ac86a63ba7ba799bd27a57d2f0/nerfstudio/field_components/neurad_encoding.py#L211

got it!Thank you very much!

**Comment by zzz5y** [comment]
> # Apply random flip if applicable

got it too!Thank you very much!

**Comment by bob020416** [comment]
Hi  @georghess  Thanks for the great work, 
so i have modify one of the actor's trajectory but the result looks not great, when we rotate this actor, same problem as this issue dicuss, the front and the other angle detail moght not been seen and train by the model 

![Screenshot 2025-01-05 at 12 45 22 PM (2)](https://github.com/user-attachments/assets/0a8cb287-5750-4c8d-8da5-15a1531e2cbc)



if we want to make the rendering of modified actor result looks better do you have any suggestion for this ? lor we can only use blender car model to replace the actor (cause i seen some other works do this )

**Comment by wjie-gogogo** [comment]
> Hi @georghess Thanks for the great work, so i have modify one of the actor's trajectory but the result looks not great, when we rotate this actor, same problem as this issue dicuss, the front and the other angle detail might not been seen and train by the model
> 
> ![Screenshot 2025-01-05 at 12 45 22 PM (2)](https://private-user-images.githubusercontent.com/82202284/400178543-0a8cb287-5750-4c8d-8da5-15a1531e2cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNTMwNjIsIm5iZiI6MTczNjA1Mjc2MiwicGF0aCI6Ii84MjIwMjI4NC80MDAxNzg1NDMtMGE4Y2IyODctNTc1MC00YzhkLThkYTUtMTVhMTUzMWUyY2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDA0NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZGI2NTU4NWU0YTBhNDY2MzEwYzhiNWYxMGI4MzEwNzQ4N2Q2MWE4NzgyODA1ZTczZmUxMDJmYWU2OTM4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.erNnMjYR7wp8fJSZ-e5Rtrxn3s_IyeUp9AcoVgTUSW4)
> 
> if we want to make the rendering of modified actor result looks better do you have any suggestion for this ? or we can only use blender car model to replace the actor (cause i seen some other works do this )

As you can see in https://github.com/georghess/neurad-studio/issues/26#issuecomment-2160490397. Neurad only add the left-right symmetry priors. And the car you has chosen can been seen only in the back. So if you want the result looks great， you can change another car like car in the left hand or you can add some generative model supervision. Aslo, in unisim ,they add a hypernetword to do this.

**Comment by bob020416** [comment]
> > Hi @georghess Thanks for the great work, so i have modify one of the actor's trajectory but the result looks not great, when we rotate this actor, same problem as this issue dicuss, the front and the other angle detail might not been seen and train by the model
> > ![Screenshot 2025-01-05 at 12 45 22 PM (2)](https://private-user-images.githubusercontent.com/82202284/400178543-0a8cb287-5750-4c8d-8da5-15a1531e2cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNTMwNjIsIm5iZiI6MTczNjA1Mjc2MiwicGF0aCI6Ii84MjIwMjI4NC80MDAxNzg1NDMtMGE4Y2IyODctNTc1MC00YzhkLThkYTUtMTVhMTUzMWUyY2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDA0NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZGI2NTU4NWU0YTBhNDY2MzEwYzhiNWYxMGI4MzEwNzQ4N2Q2MWE4NzgyODA1ZTczZmUxMDJmYWU2OTM4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.erNnMjYR7wp8fJSZ-e5Rtrxn3s_IyeUp9AcoVgTUSW4)
> > if we want to make the rendering of modified actor result looks better do you have any suggestion for this ? or we can only use blender car model to replace the actor (cause i seen some other works do this )
> 
> As you can see in [#26 (comment)](https://github.com/georghess/neurad-studio/issues/26#issuecomment-2160490397). Neurad only add the left-right symmetry priors. And the car you has chosen can been seen only in the back. So if you want the result looks great， you can change another car like car in the left hand or you can add some generative model supervision. Aslo, in unisim ,they add a hypernetwork to do this.

Thanks for your explanation, will you recommend any selection logic of actor to modified ? the one drive in the opposite lane mght be better?  and also there are multiple chose to train the model, like neurad , neurad paper and 2x, do you know which one will yield the best result ?

**Comment by wjie-gogogo** [comment]
> > > Hi @georghess Thanks for the great work, so i have modify one of the actor's trajectory but the result looks not great, when we rotate this actor, same problem as this issue dicuss, the front and the other angle detail might not been seen and train by the model
> > > ![Screenshot 2025-01-05 at 12 45 22 PM (2)](https://private-user-images.githubusercontent.com/82202284/400178543-0a8cb287-5750-4c8d-8da5-15a1531e2cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNTMwNjIsIm5iZiI6MTczNjA1Mjc2MiwicGF0aCI6Ii84MjIwMjI4NC80MDAxNzg1NDMtMGE4Y2IyODctNTc1MC00YzhkLThkYTUtMTVhMTUzMWUyY2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDA0NTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZGI2NTU4NWU0YTBhNDY2MzEwYzhiNWYxMGI4MzEwNzQ4N2Q2MWE4NzgyODA1ZTczZmUxMDJmYWU2OTM4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.erNnMjYR7wp8fJSZ-e5Rtrxn3s_IyeUp9AcoVgTUSW4)
> > > if we want to make the rendering of modified actor result looks better do you have any suggestion for this ? or we can only use blender car model to replace the actor (cause i seen some other works do this )
> > 
> > 
> > As you can see in [#26 (comment)](https://github.com/georghess/neurad-studio/issues/26#issuecomment-2160490397). Neurad only add the left-right symmetry priors. And the car you has chosen can been seen only in the back. So if you want the result looks great， you can change another car like car in the left hand or you can add some generative model supervision. Aslo, in unisim ,they add a hypernetwork to do this.
> 
> Thanks for your explanation, will you recommend any selection logic of actor to modified ? the one drive in the opposite lane mght be better? and also there are multiple chose to train the model, like neurad , neurad paper and 2x, do you know which one will yield the best result ?

Yes. the opposite lane's cars will be better. Because they have more views from mutil-camera. So just have try with the yellow car. And the car idx could be 28. And obviously, the neurad-2x will have better result. neurad-paper doesn't add the left-right symmetry, so if you want the car to look better, just use neurad and neurad-2x

**Comment by bob020416** [comment]
@wjie-gogogo I see, thank you very much. 
How do you identify the actor's index so quick ? i have to plot the 2D label of them and view the video to get insight 
do you have any tricks here ?

**Comment by wjie-gogogo** [comment]
> @wjie-gogogo I see, thank you very much. How do you identify the actor's index so quick ? i have to plot the 2D label of them and view the video to get insight do you have any tricks here ?

hah, i don't know if it is a trick, give a shift below, and then keep switching idx. You can roughly see which car is moving in the viewer.
![image](https://github.com/user-attachments/assets/e8dbb353-565f-4bb9-a137-66ce0c5f1d17)

**Comment by bob020416** [comment]
@wjie-gogogo Lol I see! Thanks for your help!!
