### ISSUE TITLE
3D Gaussian for NeuRAD 

### ISSUE THREAD

**Issue by szhang963** [georghess/neurad-studio#6]
Hi, thanks for the great work. 

Can we use the gsplat in nerfstudio as the reconstruction method for background and dynamic objects？

**Comment by georghess** [comment]
Thanks for your interest! The current code does not support gsplat for dynamic objects. We are working on this right now, but it's hard to estimate the timeline.

**Comment by LoickCh** [comment]
Hey,
Thank you for your great work.
Is it still on-board to release a "3DGS implementation supporting dynamic objects" ?
Thank you in advance,

**Comment by carlinds** [comment]
Hi,
That is still on-board. We will release the code for our recent paper on rendering camera and lidar data using 3D Gaussians: https://research.zenseact.com/publications/splatad/

The nerfstudio-code will either be released in this repo or as an external module, and our gsplat-fork will be released at https://github.com/carlinds/splatad.
